# Generated by Django 3.1 on 2021-01-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200813_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('E', 'Editor'), ('A', 'Admin')], default='Editor', max_length=6),
        ),
    ]
