# Generated by Django 3.1 on 2021-01-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('E', 'Editor'), ('A', 'Admin')], default='E', max_length=6),
        ),
    ]
