# Generated by Django 3.1 on 2021-01-07 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0011_auto_20210103_1939'),
        ('users', '0005_auto_20210107_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdEditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bird', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bird_editor', to='birds.bird')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor_bird', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='birds',
            field=models.ManyToManyField(related_name='editors', through='users.BirdEditor', to='birds.Bird'),
        ),
    ]
