# Generated by Django 3.1 on 2021-01-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0011_auto_20210103_1939'),
        ('users', '0006_auto_20210107_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birds',
            field=models.ManyToManyField(null=True, related_name='editors', through='users.BirdEditor', to='birds.Bird'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
