# Generated by Django 3.1 on 2021-07-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210614_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birds',
        ),
        migrations.DeleteModel(
            name='BirdEditor',
        ),
    ]
