# Generated by Django 3.1 on 2021-01-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0011_auto_20210103_1939'),
        ('users', '0007_auto_20210107_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birds',
            field=models.ManyToManyField(related_name='editors', through='users.BirdEditor', to='birds.Bird'),
        ),
    ]
