# Generated by Django 3.1 on 2021-07-16 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0063_auto_20210716_0641'),
        ('users', '0008_auto_20210715_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdCurrentEditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bird', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bird_current_editors', to='birds.bird')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_editor_birds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='birds',
            field=models.ManyToManyField(related_name='current_editors', through='users.BirdCurrentEditor', to='birds.Bird'),
        ),
    ]
