# Generated by Django 3.1 on 2021-07-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210716_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birds',
        ),
        migrations.DeleteModel(
            name='BirdCurrentEditor',
        ),
    ]
