# Generated by Django 3.1 on 2021-07-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210716_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='author_ptr',
        ),
        migrations.AddField(
            model_name='customuser',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
