version: '3.7'

services:
    postgis:
        image: kartoza/postgis:12.1
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"
            # NOTE the new environment variables
            - POSTGRES_USER=gisuser
            - POSTGRES_PASS=${POSTGRES_PASSWORD}
            - POSTGRES_DBNAME=gis
        volumes:
            - postgres_data:/var/lib/postgresql/data/
    web:
        image: brayanrodbajo/wikiaves_backend_web:latest
#        command: ["./wait-for-it.sh", "postgis:5432", "--", "python", "/code/manage.py", "runserver", "0.0.0.0:8000"]
        command: bash -c 'while !</dev/tcp/postgis/5432; do sleep 5; done; python /code/manage.py runserver 0.0.0.0:8000'
#        command: python /code/manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        environment:
            DJANGO_SU_NAME: ${DJANGO_SU_NAME}
            DJANGO_SU_EMAIL: ${DJANGO_SU_EMAIL}
            DJANGO_SU_PASSWORD: ${DJANGO_SU_PASSWORD}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        restart: on-failure
#        volumes:
#            - web_data:/code
        depends_on:
            - postgis

volumes:
    postgres_data:
#    web_data: