# Generated by Django 3.0.5 on 2020-08-13 18:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=500, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonNameFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CommonNameOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenced', models.CharField(choices=[('LITERATURE', 'LITERATURE'), ('MAPS', 'MAP'), ('IMAGES', 'IMAGE'), ('AUDIO', 'AUDIO'), ('VIDEO', 'VIDEO'), ('BIRD', 'BIRD')], max_length=10)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('series', models.IntegerField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('edition', models.IntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
                ('publisher', models.CharField(blank=True, max_length=13, null=True)),
                ('doi', models.URLField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('initial_page', models.IntegerField(blank=True, null=True)),
                ('last_page', models.IntegerField(blank=True, null=True)),
                ('date_accessed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'es'), ('en', 'en')], max_length=2)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('BIRD', 'BIRD'), ('FAMILY', 'FAMILY'), ('ORDER', 'ORDER')], max_length=6, null=True)),
                ('format', models.CharField(max_length=4)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('seconds', models.FloatField(blank=True, null=True)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='birds.Bird')),
            ],
        ),
        migrations.CreateModel(
            name='Reproduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reproduction', to='birds.Text')),
            ],
        ),
        migrations.CreateModel(
            name='ReferencesBird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='references_bird', to='birds.Bird')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='references_bird', to='birds.Reference')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=500, unique=True)),
                ('common_names', models.ManyToManyField(null=True, through='birds.CommonNameOrder', to='birds.Text')),
            ],
        ),
        migrations.CreateModel(
            name='Length',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('unit', models.CharField(choices=[('cm', 'cm'), ('in', 'in')], max_length=2)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='heights', to='birds.Bird')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('BIRD', 'BIRD'), ('FAMILY', 'FAMILY'), ('ORDER', 'ORDER')], max_length=6, null=True)),
                ('format', models.CharField(max_length=4)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('height', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='birds.Bird')),
            ],
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regional_differences', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identification_rd', to='birds.Text')),
                ('similar_species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identification_species', to='birds.Text')),
                ('size_shape', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identification_shape', to='birds.Text')),
            ],
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='habitat', to='birds.Text')),
            ],
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feeding', to='birds.Text')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=500, unique=True)),
                ('common_names', models.ManyToManyField(null=True, through='birds.CommonNameFamily', to='birds.Text')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='family', to='birds.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Conservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conservation', to='birds.Text')),
            ],
        ),
        migrations.AddField(
            model_name='commonnameorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_name_order', to='birds.Order'),
        ),
        migrations.AddField(
            model_name='commonnameorder',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_name_order', to='birds.Text'),
        ),
        migrations.AddField(
            model_name='commonnamefamily',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_name_family', to='birds.Family'),
        ),
        migrations.AddField(
            model_name='commonnamefamily',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_name_family', to='birds.Text'),
        ),
        migrations.CreateModel(
            name='CommonNameBird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_name_bird', to='birds.Bird')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_name_bird', to='birds.Text')),
            ],
        ),
        migrations.AddField(
            model_name='bird',
            name='behavior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='birds_beh', to='birds.Text'),
        ),
        migrations.AddField(
            model_name='bird',
            name='common_names',
            field=models.ManyToManyField(null=True, related_name='birds_cn', through='birds.CommonNameBird', to='birds.Text'),
        ),
        migrations.AddField(
            model_name='bird',
            name='conservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bird', to='birds.Conservation'),
        ),
        migrations.AddField(
            model_name='bird',
            name='curiosities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='birds_cur', to='birds.Text'),
        ),
        migrations.AddField(
            model_name='bird',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='birds_desc', to='birds.Text'),
        ),
        migrations.AddField(
            model_name='bird',
            name='distribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='birds_dist', to='birds.Text'),
        ),
        migrations.AddField(
            model_name='bird',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bird', to='birds.Family'),
        ),
        migrations.AddField(
            model_name='bird',
            name='feeding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bird', to='birds.Feeding'),
        ),
        migrations.AddField(
            model_name='bird',
            name='habitat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bird', to='birds.Habitat'),
        ),
        migrations.AddField(
            model_name='bird',
            name='identification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bird', to='birds.Identification'),
        ),
        migrations.AddField(
            model_name='bird',
            name='own_citation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bird', to='birds.Reference'),
        ),
        migrations.AddField(
            model_name='bird',
            name='references',
            field=models.ManyToManyField(related_name='bird_refs', through='birds.ReferencesBird', to='birds.Reference'),
        ),
        migrations.AddField(
            model_name='bird',
            name='reproduction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bird', to='birds.Reproduction'),
        ),
        migrations.AddField(
            model_name='bird',
            name='taxonomy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='birds_tax', to='birds.Text'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authors', to='birds.Reference')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('format', models.CharField(max_length=4)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audio', to='birds.Author')),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='singing', to='birds.Bird')),
            ],
        ),
    ]
