# Generated by Django 3.1 on 2020-08-13 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0002_auto_20200813_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='own_citation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bird', to='birds.reference'),
        ),
    ]
