# Generated by Django 3.1 on 2020-08-14 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0003_auto_20200813_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio', to='birds.author'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='bird',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='singing', to='birds.bird'),
        ),
        migrations.AlterField(
            model_name='author',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='birds.reference'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='behavior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birds_beh', to='birds.text'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='conservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bird', to='birds.conservation'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='curiosities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birds_cur', to='birds.text'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birds_desc', to='birds.text'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='distribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birds_dist', to='birds.text'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bird', to='birds.family'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='feeding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bird', to='birds.feeding'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='habitat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bird', to='birds.habitat'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='identification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bird', to='birds.identification'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='own_citation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bird', to='birds.reference'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='reproduction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bird', to='birds.reproduction'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='taxonomy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birds_tax', to='birds.text'),
        ),
        migrations.AlterField(
            model_name='commonnamebird',
            name='bird',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_name_bird', to='birds.bird'),
        ),
        migrations.AlterField(
            model_name='commonnamebird',
            name='text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_name_bird', to='birds.text'),
        ),
        migrations.AlterField(
            model_name='commonnamefamily',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_name_family', to='birds.family'),
        ),
        migrations.AlterField(
            model_name='commonnamefamily',
            name='text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_name_family', to='birds.text'),
        ),
        migrations.AlterField(
            model_name='commonnameorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_name_order', to='birds.order'),
        ),
        migrations.AlterField(
            model_name='commonnameorder',
            name='text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_name_order', to='birds.text'),
        ),
        migrations.AlterField(
            model_name='conservation',
            name='text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conservation', to='birds.text'),
        ),
        migrations.AlterField(
            model_name='family',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family', to='birds.order'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeding', to='birds.text'),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habitat', to='birds.text'),
        ),
        migrations.AlterField(
            model_name='identification',
            name='regional_differences',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identification_rd', to='birds.text'),
        ),
        migrations.AlterField(
            model_name='identification',
            name='similar_species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identification_species', to='birds.text'),
        ),
        migrations.AlterField(
            model_name='identification',
            name='size_shape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identification_shape', to='birds.text'),
        ),
        migrations.AlterField(
            model_name='image',
            name='bird',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='birds.bird'),
        ),
        migrations.AlterField(
            model_name='length',
            name='bird',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heights', to='birds.bird'),
        ),
        migrations.AlterField(
            model_name='referencesbird',
            name='bird',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references_bird', to='birds.bird'),
        ),
        migrations.AlterField(
            model_name='referencesbird',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references_bird', to='birds.reference'),
        ),
        migrations.AlterField(
            model_name='reproduction',
            name='text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reproduction', to='birds.text'),
        ),
        migrations.AlterField(
            model_name='video',
            name='bird',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='birds.bird'),
        ),
    ]
