# Generated by Django 3.1 on 2020-09-26 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0004_auto_20200813_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificNameBird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScientificNameFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScientificNameOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BooleanField(default=False)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientific_name_order', to='birds.text')),
            ],
        ),
        migrations.CreateModel(
            name='SDFemale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sdfemale', to='birds.image')),
                ('text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sdfemale', to='birds.text')),
            ],
        ),
        migrations.CreateModel(
            name='SDMale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sdmale', to='birds.image')),
                ('text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sdmale', to='birds.text')),
            ],
        ),
        migrations.CreateModel(
            name='SDSubadult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sdsubadult', to='birds.image')),
                ('text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sdsubadult', to='birds.text')),
            ],
        ),
        migrations.CreateModel(
            name='SDYouth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sdyouth', to='birds.image')),
                ('text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sdyouth', to='birds.text')),
            ],
        ),
        migrations.CreateModel(
            name='SexualDifferentiation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('female', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sexual_diff', to='birds.sdfemale')),
                ('male', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sexual_diff', to='birds.sdmale')),
                ('subadult', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sexual_diff', to='birds.sdsubadult')),
                ('youth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sexual_diff', to='birds.sdyouth')),
            ],
        ),
        migrations.RemoveField(
            model_name='commonnameorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='commonnameorder',
            name='text',
        ),
        migrations.RenameField(
            model_name='commonnamebird',
            old_name='text',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='bird',
            name='scientific_name',
        ),
        migrations.RemoveField(
            model_name='family',
            name='common_names',
        ),
        migrations.RemoveField(
            model_name='family',
            name='scientific_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='common_names',
        ),
        migrations.RemoveField(
            model_name='order',
            name='scientific_name',
        ),
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonnamebird',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CommonNameFamily',
        ),
        migrations.DeleteModel(
            name='CommonNameOrder',
        ),
        migrations.AddField(
            model_name='scientificnameorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientific_name_order', to='birds.order'),
        ),
        migrations.AddField(
            model_name='scientificnamefamily',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientific_name_family', to='birds.family'),
        ),
        migrations.AddField(
            model_name='scientificnamefamily',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientific_name_family', to='birds.text'),
        ),
        migrations.AddField(
            model_name='scientificnamebird',
            name='bird',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientific_name_bird', to='birds.bird'),
        ),
        migrations.AddField(
            model_name='scientificnamebird',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientific_name_bird', to='birds.text'),
        ),
        migrations.AddField(
            model_name='bird',
            name='scientific_names',
            field=models.ManyToManyField(related_name='birds_sn', through='birds.ScientificNameBird', to='birds.Text'),
        ),
        migrations.AddField(
            model_name='bird',
            name='sexual_differentiation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bird', to='birds.sexualdifferentiation'),
        ),
        migrations.AddField(
            model_name='family',
            name='scientific_names',
            field=models.ManyToManyField(through='birds.ScientificNameFamily', to='birds.Text'),
        ),
        migrations.AddField(
            model_name='order',
            name='scientific_names',
            field=models.ManyToManyField(through='birds.ScientificNameOrder', to='birds.Text'),
        ),
    ]
