# Generated by Django 3.1 on 2020-10-03 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0006_auto_20200926_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='common_names',
        ),
        migrations.AlterField(
            model_name='commonnamebird',
            name='bird',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_names', to='birds.bird'),
        ),
    ]
