# Generated by Django 3.1 on 2020-10-05 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0007_auto_20201003_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images_authored', to='birds.author'),
        ),
        migrations.AddField(
            model_name='video',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos_authored', to='birds.author'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audios_authored', to='birds.author'),
        ),
        migrations.AlterField(
            model_name='image',
            name='format',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
