# Generated by Django 3.1 on 2021-01-04 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0009_auto_20201123_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='identification_similar',
        ),
        migrations.AddField(
            model_name='bird',
            name='migration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bird_migration', to='birds.type'),
        ),
        migrations.AddField(
            model_name='bird',
            name='similar_species',
            field=models.ManyToManyField(blank=True, null=True, related_name='_bird_similar_species_+', to='birds.Bird'),
        ),
        migrations.AddField(
            model_name='measure',
            name='name',
            field=models.CharField(choices=[('length', 'length'), ('weight', 'weight')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bird',
            name='conservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bird_conservation', to='birds.type'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measure', to='birds.value'),
        ),
        migrations.AlterField(
            model_name='subspecies',
            name='bird',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subspecies', to='birds.bird'),
        ),
    ]
