# Generated by Django 3.1 on 2021-01-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0010_auto_20210103_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='similar_species',
            field=models.ManyToManyField(blank=True, related_name='_bird_similar_species_+', to='birds.Bird'),
        ),
    ]
