# Generated by Django 3.1 on 2021-01-10 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0011_auto_20210103_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='bird',
        ),
        migrations.CreateModel(
            name='Vocalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SONG', 'SONG'), ('CALL', 'CALL')], max_length=6)),
                ('audio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocalization', to='birds.audio')),
                ('bird', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocalizations', to='birds.bird')),
                ('long_description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocalization_long', to='birds.text')),
                ('short_description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocalization_short', to='birds.text')),
            ],
        ),
    ]
