# Generated by Django 3.1 on 2021-04-18 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0012_auto_20210110_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdimage',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='measure',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='measure',
            name='unit',
            field=models.CharField(choices=[('cm', 'cm'), ('mm', 'mm'), ('in', 'in'), ('g', 'g'), ('kg', 'kg')], max_length=2),
        ),
        migrations.AlterField(
            model_name='subspeciesname',
            name='name',
            field=models.CharField(default=1987, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution', to='birds.image')),
                ('text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution', to='birds.text')),
            ],
        ),
        migrations.AlterField(
            model_name='bird',
            name='distribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birds_dist', to='birds.distribution'),
        ),
        migrations.AlterField(
            model_name='subspecies',
            name='distribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subspecies_dist', to='birds.distribution'),
        ),
    ]
