# Generated by Django 3.1 on 2021-05-09 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0013_auto_20210418_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bird_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bird_ss', to='birds.bird')),
                ('similar_species_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ss_ss', to='birds.bird')),
                ('text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar_species', to='birds.text')),
            ],
        ),
        migrations.AlterField(
            model_name='bird',
            name='similar_species',
            field=models.ManyToManyField(blank=True, related_name='_bird_similar_species_+', through='birds.SimilarSpecies', to='birds.Bird'),
        ),
    ]
