# Generated by Django 3.1 on 2021-05-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0015_remove_bird_similar_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='similar_species',
            field=models.ManyToManyField(blank=True, related_name='_bird_similar_species_+', through='birds.SimilarSpecies', to='birds.Bird'),
        ),
    ]
