# Generated by Django 3.1 on 2021-05-09 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0016_bird_similar_species'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='similar_species',
        ),
        migrations.DeleteModel(
            name='SimilarSpecies',
        ),
    ]
