# Generated by Django 3.1 on 2021-05-09 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0018_auto_20210508_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='similar_species',
        ),
        migrations.DeleteModel(
            name='SimilarSpecies',
        ),
    ]
