# Generated by Django 3.1 on 2021-05-09 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0019_auto_20210508_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar_species', to='birds.text')),
            ],
        ),
        migrations.AddField(
            model_name='bird',
            name='similar_species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bird', to='birds.similarspecies'),
        ),
        migrations.AddField(
            model_name='bird',
            name='similar_species_class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bird_ss', to='birds.similarspecies'),
        ),
    ]
