# Generated by Django 3.1 on 2021-05-09 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0020_auto_20210508_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='similar_species_class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bird_ids', to='birds.similarspecies'),
        ),
    ]
