# Generated by Django 3.1 on 2021-05-09 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0021_auto_20210508_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdimage',
            name='subspecies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='birds.subspecies'),
        ),
        migrations.AlterField(
            model_name='birdimage',
            name='category',
            field=models.CharField(blank=True, choices=[('BIRD', 'BIRD'), ('FAMILY', 'FAMILY'), ('ORDER', 'ORDER'), ('SUBSPECIES', 'SUBSPECIES')], max_length=10, null=True),
        ),
    ]
