# Generated by Django 3.1 on 2021-05-09 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0022_auto_20210509_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorBird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors_bird', to='birds.author')),
                ('bird', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors_bird', to='birds.bird')),
            ],
        ),
        migrations.AddField(
            model_name='bird',
            name='authors',
            field=models.ManyToManyField(related_name='bird_authors', through='birds.AuthorBird', to='birds.Author'),
        ),
    ]
