# Generated by Django 3.1 on 2021-05-09 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0026_bird_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measures', to='birds.reference'),
        ),
    ]
