# Generated by Django 3.1 on 2021-05-19 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0027_measure_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='reproduction',
        ),
        migrations.DeleteModel(
            name='Reproduction',
        ),
    ]
