# Generated by Django 3.1 on 2021-05-19 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0028_auto_20210518_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='reproduction',
        ),
    ]
