# Generated by Django 3.1 on 2021-05-19 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0029_remove_type_reproduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='reproduction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reproduction', to='birds.bird'),
        ),
    ]
