# Generated by Django 3.1 on 2021-05-19 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0030_type_reproduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='identification_lengths_subs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lengths', to='birds.subspecies'),
        ),
        migrations.AddField(
            model_name='measure',
            name='identification_weights_subs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weights', to='birds.subspecies'),
        ),
    ]
