# Generated by Django 3.1 on 2021-05-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0031_auto_20210518_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='publisher',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='referenced',
            field=models.CharField(choices=[('LITERATURE', 'LITERATURE'), ('MAPS', 'MAP'), ('IMAGES', 'IMAGE'), ('AUDIO', 'AUDIO'), ('VIDEO', 'VIDEO'), ('BIRD', 'BIRD'), ('MEASURE', 'MEASURE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reference',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
