# Generated by Django 3.1 on 2021-05-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0033_auto_20210518_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(),
        ),
    ]
