# Generated by Django 3.1 on 2021-05-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0034_auto_20210524_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
