# Generated by Django 3.1 on 2021-05-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0038_auto_20210526_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.TextField(),
        ),
    ]
