# Generated by Django 3.1 on 2021-05-27 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0039_auto_20210526_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='image',
        ),
    ]
