# Generated by Django 3.1 on 2021-05-28 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0040_remove_type_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='bird_feeding',
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeding', to='birds.text')),
            ],
        ),
        migrations.AddField(
            model_name='bird',
            name='feeding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birds_feed', to='birds.feeding'),
        ),
        migrations.AddField(
            model_name='text',
            name='feeding_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='names', to='birds.feeding'),
        ),
    ]
