# Generated by Django 3.1 on 2021-05-28 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0041_auto_20210527_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='identification',
        ),
    ]
