# Generated by Django 3.1 on 2021-05-28 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0042_remove_type_identification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='reference',
        ),
    ]
