# Generated by Django 3.1 on 2021-05-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0043_remove_measure_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
