# Generated by Django 3.1 on 2021-05-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0044_measure_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocalization',
            name='xenocantoID',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
