# Generated by Django 3.1 on 2021-05-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0045_vocalization_xenocantoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdimage',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
