# Generated by Django 3.1 on 2021-06-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0046_auto_20210527_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='url',
            new_name='webpage',
        ),
        migrations.AddField(
            model_name='author',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='flicker',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
