# Generated by Django 3.1 on 2021-06-15 21:53

import birds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0047_auto_20210603_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='url',
            field=models.FileField(max_length=500, upload_to=birds.models.upload_audios),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=birds.models.upload_images_tn),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(max_length=500, upload_to=birds.models.upload_images),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=birds.models.upload_videos_tn),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.FileField(max_length=500, upload_to=birds.models.upload_videos),
        ),
    ]
