# Generated by Django 3.1 on 2021-06-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0048_auto_20210615_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='seconds',
            new_name='duration_in_seconds',
        ),
        migrations.AlterField(
            model_name='audio',
            name='format',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='format',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
