# Generated by Django 3.1 on 2021-06-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0049_auto_20210615_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocalization',
            old_name='xenocantoID',
            new_name='xenocanto_ID',
        ),
        migrations.AddField(
            model_name='vocalization',
            name='xenocanto_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='vocalization',
            constraint=models.CheckConstraint(check=models.Q(('xenocanto_url__isnull', True), ('audio__isnull', True), _connector='OR'), name='not_both_xenocanto_url_and_audio_be_not_null'),
        ),
    ]
