# Generated by Django 3.1 on 2021-06-18 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0050_auto_20210617_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xenocanto',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='vocalization',
            name='not_both_xenocanto_url_and_audio_be_not_null',
        ),
        migrations.RemoveField(
            model_name='vocalization',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='vocalization',
            name='xenocanto_ID',
        ),
        migrations.RemoveField(
            model_name='vocalization',
            name='xenocanto_url',
        ),
        migrations.AddField(
            model_name='audio',
            name='vocalization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audios', to='birds.vocalization'),
        ),
        migrations.AddField(
            model_name='xenocanto',
            name='vocalization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xenocantos', to='birds.vocalization'),
        ),
    ]
