# Generated by Django 3.1 on 2021-06-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0051_auto_20210618_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='xenocanto',
            name='XC_id',
            field=models.CharField(default='XC', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xenocanto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
