# Generated by Django 3.1 on 2021-06-26 19:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0052_auto_20210623_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='audio',
            name='location',
        ),
        migrations.RemoveField(
            model_name='birdimage',
            name='location',
        ),
        migrations.RemoveField(
            model_name='video',
            name='location',
        ),
    ]
