# Generated by Django 3.1 on 2021-06-26 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0053_auto_20210626_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audios', to='birds.location'),
        ),
        migrations.AddField(
            model_name='birdimage',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='birds.location'),
        ),
        migrations.AddField(
            model_name='video',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='birds.location'),
        ),
    ]
