# Generated by Django 3.1 on 2021-06-28 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0054_auto_20210626_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdimage',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bird_images', to='birds.text'),
        ),
    ]
