# Generated by Django 3.1 on 2021-06-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0055_birdimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='xenocanto',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
