# Generated by Django 3.1 on 2021-07-05 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0057_auto_20210705_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='feeding_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='birds.feeding'),
        ),
    ]
