# Generated by Django 3.1 on 2021-07-15 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('birds', '0058_auto_20210705_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorBird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='bird',
            name='authors',
        ),
        migrations.DeleteModel(
            name='AuthorBird',
        ),
        migrations.AddField(
            model_name='editorbird',
            name='bird',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editors_bird', to='birds.bird'),
        ),
        migrations.AddField(
            model_name='editorbird',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editors_bird', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bird',
            name='editors',
            field=models.ManyToManyField(related_name='bird_editors', through='birds.EditorBird', to=settings.AUTH_USER_MODEL),
        ),
    ]
