# Generated by Django 3.1 on 2021-07-16 11:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('birds', '0059_auto_20210715_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorbird',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 6, 27, 33, 948720)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AuthorBird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors_bird', to=settings.AUTH_USER_MODEL)),
                ('bird', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors_bird', to='birds.bird')),
            ],
        ),
        migrations.AddField(
            model_name='bird',
            name='authors',
            field=models.ManyToManyField(related_name='bird_authors', through='birds.AuthorBird', to=settings.AUTH_USER_MODEL),
        ),
    ]
