# Generated by Django 3.1 on 2021-07-16 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0062_bird_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='editors',
        ),
        migrations.AlterField(
            model_name='editorbird',
            name='bird',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editors', to='birds.bird'),
        ),
    ]
