# Generated by Django 3.1 on 2021-07-16 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('birds', '0063_auto_20210716_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='current_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birds_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
