# Generated by Django 3.1 on 2021-07-22 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210721_2317'),
        ('birds', '0064_bird_current_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='author',
        ),
        migrations.RemoveField(
            model_name='birdimage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='video',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
