# Generated by Django 3.1 on 2021-07-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0064_bird_current_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
