# Generated by Django 3.1 on 2021-07-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0066_auto_20210721_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimediaauthor',
            name='email',
            field=models.EmailField(default='1@q.com', max_length=254),
            preserve_default=False,
        ),
    ]
