# Generated by Django 3.1 on 2021-08-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0067_auto_20210722_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='endemism',
            field=models.CharField(blank=True, choices=[('ENDEMIC', 'ENDEMIC'), ('NON-ENDEMIC', 'NON-ENDEMIC'), ('NEARLY-ENDEMIC', 'NEARLY-ENDEMIC')], max_length=14, null=True),
        ),
    ]
